package com.autotune.analyzer.recommendations.model;

/**
 * This Represents tunable parameters for generating recommendations.
 * This class stores percentile values for memory, CPU, and accelerator utilization.
 * These tunables are used to fine-tune the recommendations generated by the system.
 */
public class RecommendationTunables {

    protected double memoryPercentile;
    protected double cpuPercentile;
    protected double acceleratorPercentile;

    public RecommendationTunables(double CPU_PERCENTILE, double MEMORY_PERCENTILE, double ACCELERATOR_PERCENTILE) {
        this.cpuPercentile = CPU_PERCENTILE;
        this.memoryPercentile = MEMORY_PERCENTILE;
        this.acceleratorPercentile = ACCELERATOR_PERCENTILE;
    }

    public double getMemoryPercentile() {
        return memoryPercentile;
    }

    public void setMemoryPercentile(double memoryPercentile) {
        this.memoryPercentile = memoryPercentile;
    }

    public double getCpuPercentile() {
        return cpuPercentile;
    }

    public void setCpuPercentile(double cpuPercentile) {
        this.cpuPercentile = cpuPercentile;
    }

    public double getAcceleratorPercentile() {
        return acceleratorPercentile;
    }

    public void setAcceleratorPercentile(double acceleratorPercentile) {
        this.acceleratorPercentile = acceleratorPercentile;
    }
}
