apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: autotune
  labels:
    team: autotune-frontend
spec:
  selector:
    matchLabels:
      app: autotune
  endpoints:
  - port: http
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: autotune-frontend
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false

