apiVersion: "recommender.com/v1beta1"
kind: "Autotune"
metadata:
 name: "autotunes.recommender.com"
 namespace: "autotune-operator-ns"
spec:
 replicas: 1
 sla:
   name: "response-time"
   value: "lower"
 mode: "show"
 selector: 
   matchLabel: "appname-acmeair"
   matchRoute: ""
   matchRUI: "https://localhost:8080/acmeair"
   matchService: ""

