apiVersion: apiextensions.k8s.io/v1beta1
kind: "CustomResourceDefinition"
metadata:
  #name must match the spec fields below, and be in the form: <plural>.<group>
  name: autotunequeryvariables.recommender.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: "recommender.com"
  names:
    plural: autotunequeryvariables
    singular: autotunequeryvariable
    #types can be identified with this tag
    kind: AutotuneQueryVariable
  scope: Namespaced
  version: v1beta1
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
        of an object. Servers should convert recognized schemas to the latest
        internal value, and may reject unrecognized values. More info: https://git.k8s.io/
        community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
           object represents. Servers may infer this from the endpoint the client
           submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/
           community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        query_variables:
          description: 'List of variables to be replaced in the query'
          type: array
          items:
            type: object
            properties:
              name:
                description: 'Name of the variable'
                type: string
              value:
                description: 'Value of the variable'
                type: string

